Deployment Status

diff --git a/nginx-sample/azure-pipelines.yml b/nginx-sample/azure-pipelines.yml
--- a/nginx-sample/azure-pipelines.yml
+++ b/nginx-sample/azure-pipelines.yml
@@ -84,14 +84,58 @@ stages:
         targetFolder: $(Build.BuildId)
         sourceFolder: 'nginx-sample'
         globExpressions: 'appspec.yaml'
-    - task: AWSCLI@1
-      displayName: CodeDeploy Deploy
+    - task: Bash@3
+      displayName: Update task definition & appspec
       inputs:
-        awsCredentials: 'AWS'
-        regionName: $(AWS_REGION)
-        awsCommand: 'deploy'
-        awsSubCommand: 'create-deployment'
-        awsArguments: '--cli-input-json file://nginx-sample/create-deployment.json'
+        targetType: inline
+        script: |
+          # Invoke CodeDeploy
+          export CREATE_DEPLOYMENT_OUTPUT=$(aws deploy create-deployment --cli-input-json file://nginx-sample/create-deployment.json )
+          export DEPLOYMENT_ID=$(echo $CREATE_DEPLOYMENT_OUTPUT | jq -r '.deploymentId')
+          echo 'Deployment Id: ' $DEPLOYMENT_ID
+          
+          DURATION_IN_SECONDS=1200 #20 Minutes                         
+          ENDTIME=$(( $(date +%s) + $DURATION_IN_SECONDS ))
+          SLEEP_INTERVAL="30s"
+
+          echo "Timeout Duration: $DURATION_IN_SECONDS"
+          echo "Sleep Interval between checks: $SLEEP_INTERVAL"
+          echo ""
+
+          # Available status : Created | Queued | InProgress | Baking | Succeeded | Failed | Stopped | Ready
+
+          DEPLOYMENT_SUCCESS="false"
+
+          while [ $(date +%s) -lt $ENDTIME ]; do
+            GET_DEPLOYMENT_OUTPUT=$(aws deploy get-deployment \
+              --deployment-id  $DEPLOYMENT_ID)
+
+            DEPLOYMENT_STATUS=$(echo $GET_DEPLOYMENT_OUTPUT | jq '.status')
+
+            if [[ $DEPLOYMENT_STATUS = 'Succeeded']]; then
+              DEPLOYMENT_SUCCESS="true"
+              echo "Deployment Completed."
+              break
+            elif [[ $DEPLOYMENT_STATUS = 'Failed']] || [[ $DEPLOYMENT_STATUS = 'Stopped']]
+              then
+              echo "Deployment " $DEPLOYMENT_STATUS
+              break
+            else
+              echo "New Task Set Status: $DEPLOYMENT_STATUS"
+            fi
+
+            sleep $SLEEP_INTERVAL
+          done
+
+          if [[ $DEPLOYMENT_SUCCESS = "false" ]]; then
+            echo "ERROR:  Deployment Failed . Please check CodeDeploy Console"
+            exit 1
+          fi
+        env:
+          AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
+          AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
+          AWS_DEFAULT_REGION: $(AWS_REGION)
+
 
 
       
